name: movie_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  fpdart: ^1.1.1
  flutter_svg: ^2.0.16
  get: ^4.6.6
  flutter_screenutil: ^5.9.3  
  flutter_animate: ^4.5.2
  permission_handler: ^11.3.1
  cached_network_image: ^3.4.1
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.14
  path_provider: ^2.1.5
  connectivity_plus: ^6.1.2
  retry: ^3.1.2
  readmore: ^3.0.0
  url_launcher: ^6.3.1
  timezone: ^0.10.0
  flutter_spinkit: ^5.2.1
  carousel_slider: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/svgs/

  fonts:
      - family: Almarai
        fonts:
          - asset: assets/fonts/Almarai-Bold.ttf
            # style: bold
            weight: 700
          - asset: assets/fonts/Almarai-Regular.ttf
            # style: normal
            weight: 400